### ISSUE TITLE
关于EX部分内容书签无法查看的问题

### ISSUE THREAD

**Issue by 21126881** [21126881/panda#5]
近期EX进行了系统更新，系统规则有了一些变更。
在此之前如果能进入里站，部分内容只根据IP所在地进行屏蔽。如果账号被封，如果里站COOKIE依然有效，则仍可以查看相关内容。现在即便COOKIE有效，依然能够登录里站，如果账号被封或等级不足，也无法查看。
简单来说就比如当前书签账号等级不足以进入里站，即便能用COOKIE强制进入，能够查看的内容也和表站没有差异，因此公共账号丧失了本来的意义。我们采取的临时措施是将一键解锁的账号拿来用于书签，并寻找商家购买新的高权限账号。
当然绑定私人账号可避免此类问题出现，强烈建议使用私人账号登录里站。

**Comment by DrAClef** [comment]
感谢制作组的分享和解释！

**Comment by ksu4040e064** [comment]
好像已经解锁了
